---

work_dir_name: rhpam-dev
ocp_project: "rhpam-dev-{{ ocp_user }}"
ocp_project_display_name: "RHPAM-dev"
ocp_project_desc: "RHPAM dev environment"

resources_dir: "{{ resources_home_dir }}/rhpam"

uninstall_delete_project: True
